
backend:
  name: github
  repo: fboamorte/stpfran-site1
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "_produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome do Produto", name: "title", widget: "string" }
      - { label: "Descrição", name: "body", widget: "markdown" }
